name: Build Rify Windows

on:
  push:
    tags:
      - "v*"

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4


      - name: Install MSYS2 GTK + Python
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >-
            mingw-w64-ucrt-x86_64-python
            mingw-w64-ucrt-x86_64-python-pip
            mingw-w64-ucrt-x86_64-python-gobject
            mingw-w64-ucrt-x86_64-gtk4


      - name: Prepare GTK runtime
        shell: powershell
        run: |
          New-Item -ItemType Directory -Force runtime\gtk | Out-Null

          xcopy C:\msys64\ucrt64\bin runtime\gtk\bin /E /I /Y
          xcopy C:\msys64\ucrt64\share runtime\gtk\share /E /I /Y


      - name: Check mpv runtime
        shell: powershell
        run: |
          if (!(Test-Path "runtime\mpv\mpv.7z")) {
              Write-Error "mpv.7z missing!"
              exit 1
          }


      - name: Extract mpv
        shell: powershell
        run: |
          7z x runtime\mpv\mpv.7z -oruntime\mpv -y


      - name: Build Rify with MSYS2 Python
        shell: msys2 {0}
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pyinstaller

          python -m PyInstaller \
            --windowed \
            --onedir \
            --name Rify \
            --collect-all gi \
            --hidden-import=gi.repository.Gtk \
            --hidden-import=gi.repository.GLib \
            main.py


      - name: Copy mpv DLLs
        shell: powershell
        run: |
          Copy-Item runtime\mpv\*.dll dist\Rify\ -ErrorAction SilentlyContinue
          Copy-Item runtime\mpv\**\*.dll dist\Rify\ -ErrorAction SilentlyContinue


      - name: Copy GTK runtime
        shell: powershell
        run: |
          Copy-Item runtime\gtk\bin\*.dll dist\Rify\ -Recurse -Force -ErrorAction SilentlyContinue

          Copy-Item runtime\gtk\share dist\Rify\share `
            -Recurse `
            -Force `
            -ErrorAction SilentlyContinue


      - name: Package Rify
        shell: powershell
        run: |
          Compress-Archive `
          -Path dist\Rify\* `
          -DestinationPath Rify-Windows.zip


      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Rify-Windows
          path: Rify-Windows.zip 